* Description
The *grep-notes* command provides a quick & easy way to view notes associated
with the current context. The *grep-notes-file-assoc* option is used to specify
which file to use for grepping based on the current major-mode or some other
condition.
* Installation

 - Put the library in a directory in the emacs load path, like ~/.emacs.d
 - You can add a directory to your load-path with the following line in ~/.emacs
   (add-to-list 'load-path (expand-file-name "~/elisp"))
   where ~/elisp is the directory you want to add 
   (you don't need to do this for ~/.emacs.d - it's added by default).
 - Add the following to your ~/.emacs startup file: (require 'grep-notes)
* Commands & keybindings

 Below is a complete list of commands:

   - *grep-notes* :
    grep for matches to REGEX between STARTLINE and ENDLINE in FILE.\\
    Keybinding: =M-x grep-notes=
   - *grep-notes-toggle-invisibility*
    Toggle which parts of the *grep* buffer are invisible.
    Keybinding: t

* Customizable Options

 Below is a list of customizable options:

   - *grep-notes-default-file* :
    Default file to use for  - *grep-notes* : command when there is no file associated with the current buffer in *grep-notes-file-assoc*
   - *grep-notes-file-assoc*
    Assoc list of the form (COND . (FILE REGIONS OPTIONS)) for use with *grep-notes* command.
    default = nil
   - *grep-notes-default-options*
    Extra options for grep searches when no extra options are given by *grep-notes-file-assoc* entry.
    default = "-i"
   - *grep-notes-invisibility-spec*
    Indicate which parts of the *grep* buffer to hide by default.
    default = (quote (t other))
   - *grep-notes-skip-missing-regions*
    If non-nil then if any regexp delimited region cannot be found it will be skipped.
    default = nil
   - *grep-note-more-manpages*
    If non-nil then *grep-notes-guess-manpages* will be less restrictive in its choice of manpages.
    default = t
